server {
    listen 80;
    server_name localhost;

    default_type application/json;

    location = /mobilites-stationnement-des-parkings-en-temps-reel/lines {
        alias /data/Cannes_data.json;
    }
}
